### PR TITLE
Distribute libcrypto derivatives for x86_64

### PR DESCRIPTION
**Pull request by zyrolasting**
Addresses #31

Replace `xiden/openssl` with `xiden/crypto`, and back it with one `x86_64` dynamic library for Windows, Linux, and macOS. Tested locally on macOS Catalina. 

@countvajhula Sorry for the long turnaround. If you have a moment, could you please check out this branch, install it as a package, then try running `raco test crypto.rkt`? That isn't strictly necessary, but I'd like to know if you can reproduce passing tests on your machine for the extra confidence. If the tests pass, or if I don't hear back in a few days, I'll merge this PR to unblock your progress in the guide.

### CODE REVIEW

**Comment by countvajhula** [comment]
Nice @zyrolasting , happy to try again.

I fetched the latest repo and checked out the libcrypto branch. Then,
1. `raco pkg remove xiden` to remove the currently-installed version
2. `raco pkg install --deps search-auto` to install afresh from the current directory

This resulted in:
```
system-type: contract violation
  expected: (or/c 'os 'word 'vm 'gc 'link 'machine 'target-machine
                  'so-suffix 'so-mode 'fs-change 'cross)
  given: 'arch
  context...:
   do-raise-argument-error
   proc
   call-in-empty-metacontinuation-frame
   body of "/Users/siddhartha/work/lisp/racket/xiden/crypto.rkt"
   temp35_0
   run-module-instance!
   [repeats 2 more times]
   perform-require!
   loop
   [repeats 1 more time]
   finish
   [repeats 4 more times]
   pass-1-and-2-loop
   module-begin-k
   expand-module
   expand-capturing-lifts
```

Let me know if you think I'm doing something wrong.

**Comment by countvajhula** [comment]
Looks like `arch` is a flag supported [starting in Racket 7.9](https://docs.racket-lang.org/reference/runtime.html?q=system-type#%28def._%28%28quote._~23~25kernel%29._system-type%29%29). I'm on 7.8 at the moment. Do you intend to support 7.8? I could upgrade my Racket version if necessary.

**Comment by countvajhula** [comment]
Just tried to reinstall with the new commit you added. You may be in the middle of fixing this already but just in case, looks like a path may be hardcoded somewhere:

```
raco setup: 3 making: <pkgs>/xiden
ffi-lib: could not load foreign library
  path: /Users/siddhartha/work/lisp/racket/xiden/crypto/x86_64-macosx/crypto.dylib
  system error: dlopen(/Users/siddhartha/work/lisp/racket/xiden/crypto/x86_64-macosx/crypto.dylib, 6): Library not loaded: /Users/sage/xiden/crypto/dist/lib/libcrypto.3.dylib
  Referenced from: /Users/siddhartha/work/lisp/racket/xiden/crypto/x86_64-macosx/crypto.dylib
  Reason: image not found
  context...:
   raise-dll-error
   .../ffi/unsafe.rkt:131:0: get-ffi-lib
   proc
   call-in-empty-metacontinuation-frame
   body of "/Users/siddhartha/work/lisp/racket/xiden/crypto.rkt"
   temp35_0
   run-module-instance!
   [repeats 2 more times]
   perform-require!
   loop
   [repeats 1 more time]
   finish
   [repeats 4 more times]
   pass-1-and-2-loop
   module-begin-k
   expand-module

```

**Comment by zyrolasting** [comment]
_Sigh_, yes, the `dylib` ended up with a hard-coded path post-compilation. I'm sorry that we keep running into works-on-my-machine bugs, but I am grateful that you are willing to keep trying. Thank you.

I'm checking on what I did wrong today and will incorporate a second user account to verify that this bug was fixed.

**Comment by zyrolasting** [comment]
@countvajhula Found what might be the issue after reading https://gist.github.com/loderunner/b6846dd82967ac048439

Apparently the macOS' implementation of `ld` will always prefer dynamic libraries without prompt if a static and a dynamic library appear in the same directory. Some hard-coded paths remain for similar reasons, but I do not think any of them are affect Xiden. Pull, then try `raco test crypto.rkt` again when ready.

**Comment by zyrolasting** [comment]
On second thought, the state of the project has macOS as an outlier at this point. I'll merge for now, and we can bring new error reports to issue discussions,

**Comment by countvajhula** [comment]
No worries at all. I like getting reports from people encountering issues with code I've written, and makes me more confident that the code is robust, so I'm glad to be in a position to uncover some of those corner cases here. Also, I want xiden to succeed -- having a functional versioning and dependency manager seems like a no-brainer to me, and something that, as a library author, I find myself wishing for often. I'll try again and if I run into additional issues, I'll report them. Thanks again for your efforts 👍

**Pull request merged**
